### ISSUE TITLE
IllegalStateException in PostgisConverter

### ISSUE THREAD

**Issue by nklose** [realityforge/geolatte-geom-jpa#2]
Hi again, I'm getting an IllegalStateException that I can't seem to resolve. Details:
```
SEVERE: Servlet.service() for servlet [appServlet] in context with path [/NatureLynxV03] threw exception
[Request processing failed; nested exception is javax.persistence.PersistenceException: An exception
occurred while calling convertToEntityAttribute on converter class
org.realityforge.jeo.geolatte.jpa.PostgisConverter with value (-113.03531,54.23346)] with root cause
java.lang.IllegalStateException
at org.realityforge.jeo.geolatte.jpa.PostgisConverter.convertToEntityAttribute(PostgisConverter.java:53)
at org.realityforge.jeo.geolatte.jpa.PostgisConverter.convertToEntityAttribute(PostgisConverter.java:14)
```
I'm using the PostgisConverter as follows:
```
@Column(name="location") @Convert(converter=PostgisConverter.class)
private org.geolatte.geom.Point location;
```
That column maps to a PostGIS Geometry POINT type. I'd be very grateful if you could assist!

**Comment by realityforge** [comment]
It is difficult to guess at this - you may need to open up a debugger put a break point and see the type of the value flowing through the converter. However I suspect you have not set up the database driver correctly. You need to add the postgis library to the same classloader as the postgres database driver.  i.e. Make sure you add the library https://github.com/realityforge/geolatte-geom-jpa/blob/master/build.yaml#L17 in the same place you add the postgres driver https://github.com/realityforge/geolatte-geom-jpa/blob/master/build.yaml#L16

**Comment by nklose** [comment]
Thanks for your reply! I'm using `pom.xml` instead of `build.yaml` to specify the driver, but it and the other Geolatte dependencies are all listed there and being included in the build. The project works fine if I omit the one column that uses Geolatte, so I believe the driver is set up properly.
